### ISSUE TITLE
please fix please im begging you

### ISSUE THREAD

**Issue by vtmnscope** [ToXicVibezz/AFTERMATH#12]
The whole battleye thing is like not cool and wont let you go into a public lobby. I know this menu is mainly yim but stand bypassed this bug and i was wondering if you could too? it would be awsome

**Comment by ToXicVibezz** [comment]
This menu consists of merges from multiple menus besides Yim. Stand doesn’t do anything that is different, pinkeye rat is just that . It only injects the same FSL that everyone else gets from unknowncheats. Besides that the menu lets you go into any lobby without being removed occasionally as long as your host. The launchpad that’s is available in the Discord automatically handles all of these things by automatically updating needed files.

**Comment by vtmnscope** [comment]
What discord?



________________________________
