### ISSUE TITLE
build 3179

### ISSUE THREAD

**Issue by ddk357** [ToXicVibezz/AFTERMATH#2]
hello! first of all, your menu is awesome! started using it recently, love it a lot. the issue is after the latest update (build 3179) menu crashes the game after injection. i think you know it, its just that i cannot find your discord channel/etc. If you dont have it, i think you definetly should, cause your menu is great

**Comment by ToXicVibezz** [comment]
> hello! first of all, your menu is awesome! started using it recently, love it a lot. the issue is after the latest update (build 3179) menu crashes the game after injection. i think you know it, its just that i cannot find your discord channel/etc. If you dont have it, i think you definetly should, cause your menu is great

Sorry Ive update it since and it should be on now .. im working on adding new features and removing / replacing existing ones. <https://discord.gg/ANbQ2WGD6j>

**Comment by ToXicVibezz** [comment]
01bba92f871da0513c2515532417a96e03f0bad1
