### ISSUE TITLE
The best protection is in your menu,

### ISSUE THREAD

**Issue by vtity** [ToXicVibezz/AFTERMATH#5]
so when will ur menu will be available again sir :)

**Comment by ToXicVibezz** [comment]
> so when will ur menu will be available again sir :)

As soon as you inject it.. Menu is up to date shortly after update

**Comment by ToXicVibezz** [comment]
> uhm i cant inject it, nothing happens. but i will try another injector maybe

Either Turn off Real Time protection/ + unblock dll & process. or Update your PC. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
